#!/usr/bin/python3.12
from turtle import *
from math import pi, sin, cos
import sys

hideturtle()
setup(width=1024, height=1024)
s = Screen()
s.bgcolor('black')
pencolor('white')

V = int(sys.argv[1])
R = 300
angles = [2*pi / V * i + pi/2 - 2*pi/V for i in range(1, V+1)]
points = [(R*cos(theta), R*sin(theta)) for theta in angles]

penup()
goto(points[0])
pendown()
width(6)
for p in points[1:] + [points[0]]:
    goto(*p)

for i in range(V-2):
    for j in range(i+2, V):
        penup()
        goto(*points[i])
        pendown()
        goto(*points[j])
        penup()

mainloop()