#!/usr/bin/python3.12
import tkinter as tk

def create_circle(canvas, x, y, r, **kwargs):
    """Create a circle on the canvas at position (x, y) with radius r"""
    return canvas.create_oval(x-r, y-r, x+r, y+r, **kwargs)

root = tk.Tk()
root.title("Tkinter Circle")
root.geometry("1920x1080")

canvas = tk.Canvas(root, width=1920, height=1080, bg="black")
canvas.pack(fill="both", expand=True)

from math import pi,sin,cos
import sys
if len(sys.argv) < 3:
    print('Two arguments are needed: the radius of the circles, and the width of the pen.')
    exit(1)
r,w = map(int, sys.argv[1:3])
cx,cy = 960,540
create_circle(canvas, cx, cy, r, outline='white', width=w)
angles = [pi/6 + k * pi/3 for k in range(6)]

centers = [(cx,cy)]

for theta in angles:
    for i in map(lambda k:2*k, range(1,3)):
        p = (cx + i*r*cos(theta), cy+i*r*sin(theta))
        create_circle(canvas, *p, r, outline='white', width=w)
        centers.append(p)

for i in range(len(centers)-1):
    for j in range(i+1, len(centers)):
        canvas.create_line(*centers[i], *centers[j], fill='white', width=w)

root.mainloop()
